### ISSUE TITLE
Multi Driver Capability

### ISSUE THREAD

**Issue by TroyManary** [TroyManary/EasyPlow#53]
Need to add the ability for Companies to manage multiple drivers in multiple service areas.

The feature is described in:
    Google Drive\EASYPLOW SHARED\03 Requirements\Multi Driver Feature.pptx
It includes recommendations for UI and Database changes to accommodate multi-drive.

The official UI Design provided by Brendan is here:
     Google Drive\EASYPLOW SHARED\04 UI Development\Web Design V1 - Mockups\Change Requests\Multi Driver
    Google Drive\EASYPLOW SHARED\04 UI Development\Mobile Design V1 - Mockups\Change Requests\Multi Driver

**Comment by TroyManary** [comment]
Set Priority to High since this is the most important feature to get implemented now - higher than Customer Registration.
Operators will be coming to our site to begin registering. Those companies with several drivers will need this capability.

**Comment by rachelle-eplow** [comment]
As soon as it's ready I will QA the function                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Virgin Mobile network.                                                                                                                                                                                                                From: Troy ManarySent: Friday, September 11, 2015 9:45 AMTo: TroyManary/EasyPlowReply To: TroyManary/EasyPlowSubject: Re: [EasyPlow] Multi Driver Capability (#53)Set Priority to High since this is the most important feature to get implemented now - higher than Customer Registration.
Operators will be coming to our site to begin registering. Those companies with several drivers will need this capability.

—Reply to this email directly or view it on GitHub.

**Comment by AlexEdimensionz** [comment]
Ready to go

**Comment by TroyManary** [comment]
Verified on Staging and Closed
